/**
 * Singapore MRT + LRT station names (operational only).
 * Sources:
 * - https://en.wikipedia.org/wiki/List_of_Singapore_MRT_stations
 * - https://en.wikipedia.org/wiki/List_of_Singapore_LRT_stations
 * Generated: 2026-06-21 — run `deno task generate:mrt-stations` to refresh.
 * DO NOT EDIT — changes will be overwritten.
 */
export const MRT_LRT_STATIONS = [
  "Admiralty",
  "Aljunied",
  "Ang Mo Kio",
  "Bakau",
  "Bangkit",
  "Bartley",
  "Bayfront",
  "Bayshore",
  "Beauty World",
  "Bedok",
  "Bedok North",
  "Bedok Reservoir",
  "Bencoolen",
  "Bendemeer",
  "Bishan",
  "Boon Keng",
  "Boon Lay",
  "Botanic Gardens",
  "Braddell",
  "Bras Basah",
  "Bright Hill",
  "Buangkok",
  "Bugis",
  "Bukit Batok",
  "Bukit Brown",
  "Bukit Gombak",
  "Bukit Panjang",
  "Buona Vista",
  "Caldecott",
  "Canberra",
  "Cashew",
  "Changi Airport",
  "Cheng Lim",
  "Chinatown",
  "Chinese Garden",
  "Choa Chu Kang",
  "City Hall",
  "Clarke Quay",
  "Clementi",
  "Commonwealth",
  "Compassvale",
  "Coral Edge",
  "Cove",
  "Dakota",
  "Damai",
  "Dhoby Ghaut",
  "Dover",
  "Esplanade",
  "Eunos",
  "Expo",
  "Fajar",
  "Farmway",
  "Farrer Park",
  "Farrer Road",
  "Fernvale",
  "Fort Canning",
  "Gardens by the Bay",
  "Geylang Bahru",
  "Great World",
  "Gul Circle",
  "HarbourFront",
  "Havelock",
  "Haw Par Villa",
  "Hillview",
  "Holland Village",
  "Hougang",
  "Hume",
  "Jalan Besar",
  "Jelapang",
  "Joo Koon",
  "Jurong East",
  "Kadaloor",
  "Kaki Bukit",
  "Kallang",
  "Kangkar",
  "Katong Park",
  "Keat Hong",
  "Kembangan",
  "Kent Ridge",
  "Khatib",
  "King Albert Park",
  "Kovan",
  "Kranji",
  "Kupang",
  "Labrador Park",
  "Lakeside",
  "Lavender",
  "Layar",
  "Lentor",
  "Little India",
  "Lorong Chuan",
  "MacPherson",
  "Marina Bay",
  "Marina South",
  "Marina South Pier",
  "Marine Parade",
  "Marine Terrace",
  "Marsiling",
  "Marymount",
  "Mattar",
  "Maxwell",
  "Mayflower",
  "Meridian",
  "Mount Pleasant",
  "Mountbatten",
  "Napier",
  "Newton",
  "Nibong",
  "Nicoll Highway",
  "Novena",
  "Oasis",
  "one-north",
  "Orchard",
  "Orchard Boulevard",
  "Outram Park",
  "Pasir Panjang",
  "Pasir Ris",
  "Paya Lebar",
  "Pending",
  "Petir",
  "Phoenix",
  "Pioneer",
  "Potong Pasir",
  "Promenade",
  "Punggol",
  "Punggol Coast",
  "Punggol Point",
  "Queenstown",
  "Raffles Place",
  "Ranggung",
  "Redhill",
  "Renjong",
  "Riviera",
  "Rochor",
  "Rumbia",
  "Sam Kee",
  "Samudera",
  "Segar",
  "Sembawang",
  "Sengkang",
  "Senja",
  "Serangoon",
  "Shenton Way",
  "Siglap",
  "Simei",
  "Sixth Avenue",
  "Somerset",
  "Soo Teck",
  "South View",
  "Springleaf",
  "Stadium",
  "Stevens",
  "Sumang",
  "Tagore",
  "Tai Seng",
  "Tampines",
  "Tampines East",
  "Tampines West",
  "Tan Kah Kee",
  "Tanah Merah",
  "Tanjong Katong",
  "Tanjong Pagar",
  "Tanjong Rhu",
  "Teck Lee",
  "Teck Whye",
  "Telok Ayer",
  "Telok Blangah",
  "Thanggam",
  "Tiong Bahru",
  "Toa Payoh",
  "Tongkang",
  "Tuas Crescent",
  "Tuas Link",
  "Tuas West Road",
  "Ubi",
  "Upper Changi",
  "Upper Thomson",
  "Woodlands",
  "Woodlands North",
  "Woodlands South",
  "Woodleigh",
  "Yew Tee",
  "Yio Chu Kang",
  "Yishun",
] as const;

export const MRT_LRT_STATION_COUNT = MRT_LRT_STATIONS.length;
