/**
 * Singapore MRT + LRT stations (operational only) with their line codes.
 * Sources:
 * - https://en.wikipedia.org/wiki/List_of_Singapore_MRT_stations
 * - https://en.wikipedia.org/wiki/List_of_Singapore_LRT_stations
 * Generated: 2026-07-04 — run `deno task generate:mrt-stations` to refresh.
 * DO NOT EDIT — changes will be overwritten.
 */
export interface GeneratedStationEntry {
  name: string;
  /** Line codes in alphabetical order (e.g. Dhoby Ghaut: CC1, NE6, NS24). */
  codes: readonly string[];
  onMrtList: boolean;
  onLrtList: boolean;
}

export const MRT_LRT_STATION_ENTRIES: readonly GeneratedStationEntry[] = [
  { name: "Admiralty", codes: ["NS10"], onMrtList: true, onLrtList: false },
  { name: "Aljunied", codes: ["EW9"], onMrtList: true, onLrtList: false },
  { name: "Ang Mo Kio", codes: ["NS16"], onMrtList: true, onLrtList: false },
  { name: "Bakau", codes: ["SE3"], onMrtList: false, onLrtList: true },
  { name: "Bangkit", codes: ["BP9"], onMrtList: false, onLrtList: true },
  { name: "Bartley", codes: ["CC12"], onMrtList: true, onLrtList: false },
  { name: "Bayfront", codes: ["CE1", "DT16"], onMrtList: true, onLrtList: false },
  { name: "Bayshore", codes: ["TE29"], onMrtList: true, onLrtList: false },
  { name: "Beauty World", codes: ["DT5"], onMrtList: true, onLrtList: false },
  { name: "Bedok", codes: ["EW5"], onMrtList: true, onLrtList: false },
  { name: "Bedok North", codes: ["DT29"], onMrtList: true, onLrtList: false },
  { name: "Bedok Reservoir", codes: ["DT30"], onMrtList: true, onLrtList: false },
  { name: "Bencoolen", codes: ["DT21"], onMrtList: true, onLrtList: false },
  { name: "Bendemeer", codes: ["DT23"], onMrtList: true, onLrtList: false },
  { name: "Bishan", codes: ["CC15", "NS17"], onMrtList: true, onLrtList: false },
  { name: "Boon Keng", codes: ["NE9"], onMrtList: true, onLrtList: false },
  { name: "Boon Lay", codes: ["EW27"], onMrtList: true, onLrtList: false },
  { name: "Botanic Gardens", codes: ["CC19", "DT9"], onMrtList: true, onLrtList: false },
  { name: "Braddell", codes: ["NS18"], onMrtList: true, onLrtList: false },
  { name: "Bras Basah", codes: ["CC2"], onMrtList: true, onLrtList: false },
  { name: "Bright Hill", codes: ["TE7"], onMrtList: true, onLrtList: false },
  { name: "Buangkok", codes: ["NE15"], onMrtList: true, onLrtList: false },
  { name: "Bugis", codes: ["DT14", "EW12"], onMrtList: true, onLrtList: false },
  { name: "Bukit Batok", codes: ["NS2"], onMrtList: true, onLrtList: false },
  { name: "Bukit Brown", codes: ["CC18"], onMrtList: true, onLrtList: false },
  { name: "Bukit Gombak", codes: ["NS3"], onMrtList: true, onLrtList: false },
  { name: "Bukit Panjang", codes: ["BP6", "DT1"], onMrtList: true, onLrtList: true },
  { name: "Buona Vista", codes: ["CC22", "EW21"], onMrtList: true, onLrtList: false },
  { name: "Caldecott", codes: ["CC17", "TE9"], onMrtList: true, onLrtList: false },
  { name: "Canberra", codes: ["NS12"], onMrtList: true, onLrtList: false },
  { name: "Cashew", codes: ["DT2"], onMrtList: true, onLrtList: false },
  { name: "Changi Airport", codes: ["CG2"], onMrtList: true, onLrtList: false },
  { name: "Cheng Lim", codes: ["SW1"], onMrtList: false, onLrtList: true },
  { name: "Chinatown", codes: ["DT19", "NE4"], onMrtList: true, onLrtList: false },
  { name: "Chinese Garden", codes: ["EW25"], onMrtList: true, onLrtList: false },
  { name: "Choa Chu Kang", codes: ["BP1", "NS4"], onMrtList: true, onLrtList: true },
  { name: "City Hall", codes: ["EW13", "NS25"], onMrtList: true, onLrtList: false },
  { name: "Clarke Quay", codes: ["NE5"], onMrtList: true, onLrtList: false },
  { name: "Clementi", codes: ["EW23"], onMrtList: true, onLrtList: false },
  { name: "Commonwealth", codes: ["EW20"], onMrtList: true, onLrtList: false },
  { name: "Compassvale", codes: ["SE1"], onMrtList: false, onLrtList: true },
  { name: "Coral Edge", codes: ["PE3"], onMrtList: false, onLrtList: true },
  { name: "Cove", codes: ["PE1"], onMrtList: false, onLrtList: true },
  { name: "Dakota", codes: ["CC8"], onMrtList: true, onLrtList: false },
  { name: "Damai", codes: ["PE7"], onMrtList: false, onLrtList: true },
  { name: "Dhoby Ghaut", codes: ["CC1", "NE6", "NS24"], onMrtList: true, onLrtList: false },
  { name: "Dover", codes: ["EW22"], onMrtList: true, onLrtList: false },
  { name: "Esplanade", codes: ["CC3"], onMrtList: true, onLrtList: false },
  { name: "Eunos", codes: ["EW7"], onMrtList: true, onLrtList: false },
  { name: "Expo", codes: ["CG1", "DT35"], onMrtList: true, onLrtList: false },
  { name: "Fajar", codes: ["BP10"], onMrtList: false, onLrtList: true },
  { name: "Farmway", codes: ["SW2"], onMrtList: false, onLrtList: true },
  { name: "Farrer Park", codes: ["NE8"], onMrtList: true, onLrtList: false },
  { name: "Farrer Road", codes: ["CC20"], onMrtList: true, onLrtList: false },
  { name: "Fernvale", codes: ["SW5"], onMrtList: false, onLrtList: true },
  { name: "Fort Canning", codes: ["DT20"], onMrtList: true, onLrtList: false },
  { name: "Gardens by the Bay", codes: ["TE22"], onMrtList: true, onLrtList: false },
  { name: "Geylang Bahru", codes: ["DT24"], onMrtList: true, onLrtList: false },
  { name: "Great World", codes: ["TE15"], onMrtList: true, onLrtList: false },
  { name: "Gul Circle", codes: ["EW30"], onMrtList: true, onLrtList: false },
  { name: "HarbourFront", codes: ["CC29", "NE1"], onMrtList: true, onLrtList: false },
  { name: "Havelock", codes: ["TE16"], onMrtList: true, onLrtList: false },
  { name: "Haw Par Villa", codes: ["CC25"], onMrtList: true, onLrtList: false },
  { name: "Hillview", codes: ["DT3"], onMrtList: true, onLrtList: false },
  { name: "Holland Village", codes: ["CC21"], onMrtList: true, onLrtList: false },
  { name: "Hougang", codes: ["NE14"], onMrtList: true, onLrtList: false },
  { name: "Hume", codes: ["DT4"], onMrtList: true, onLrtList: false },
  { name: "Jalan Besar", codes: ["DT22"], onMrtList: true, onLrtList: false },
  { name: "Jelapang", codes: ["BP12"], onMrtList: false, onLrtList: true },
  { name: "Joo Koon", codes: ["EW29"], onMrtList: true, onLrtList: false },
  { name: "Jurong East", codes: ["EW24", "NS1"], onMrtList: true, onLrtList: false },
  { name: "Kadaloor", codes: ["PE5"], onMrtList: false, onLrtList: true },
  { name: "Kaki Bukit", codes: ["DT28"], onMrtList: true, onLrtList: false },
  { name: "Kallang", codes: ["EW10"], onMrtList: true, onLrtList: false },
  { name: "Kangkar", codes: ["SE4"], onMrtList: false, onLrtList: true },
  { name: "Katong Park", codes: ["TE24"], onMrtList: true, onLrtList: false },
  { name: "Keat Hong", codes: ["BP3"], onMrtList: false, onLrtList: true },
  { name: "Kembangan", codes: ["EW6"], onMrtList: true, onLrtList: false },
  { name: "Kent Ridge", codes: ["CC24"], onMrtList: true, onLrtList: false },
  { name: "Khatib", codes: ["NS14"], onMrtList: true, onLrtList: false },
  { name: "King Albert Park", codes: ["DT6"], onMrtList: true, onLrtList: false },
  { name: "Kovan", codes: ["NE13"], onMrtList: true, onLrtList: false },
  { name: "Kranji", codes: ["NS7"], onMrtList: true, onLrtList: false },
  { name: "Kupang", codes: ["SW3"], onMrtList: false, onLrtList: true },
  { name: "Labrador Park", codes: ["CC27"], onMrtList: true, onLrtList: false },
  { name: "Lakeside", codes: ["EW26"], onMrtList: true, onLrtList: false },
  { name: "Lavender", codes: ["EW11"], onMrtList: true, onLrtList: false },
  { name: "Layar", codes: ["SW6"], onMrtList: false, onLrtList: true },
  { name: "Lentor", codes: ["TE5"], onMrtList: true, onLrtList: false },
  { name: "Little India", codes: ["DT12", "NE7"], onMrtList: true, onLrtList: false },
  { name: "Lorong Chuan", codes: ["CC14"], onMrtList: true, onLrtList: false },
  { name: "MacPherson", codes: ["CC10", "DT26"], onMrtList: true, onLrtList: false },
  { name: "Marina Bay", codes: ["CE2", "NS27", "TE20"], onMrtList: true, onLrtList: false },
  { name: "Marina South", codes: ["TE21"], onMrtList: true, onLrtList: false },
  { name: "Marina South Pier", codes: ["NS28"], onMrtList: true, onLrtList: false },
  { name: "Marine Parade", codes: ["TE26"], onMrtList: true, onLrtList: false },
  { name: "Marine Terrace", codes: ["TE27"], onMrtList: true, onLrtList: false },
  { name: "Marsiling", codes: ["NS8"], onMrtList: true, onLrtList: false },
  { name: "Marymount", codes: ["CC16"], onMrtList: true, onLrtList: false },
  { name: "Mattar", codes: ["DT25"], onMrtList: true, onLrtList: false },
  { name: "Maxwell", codes: ["TE18"], onMrtList: true, onLrtList: false },
  { name: "Mayflower", codes: ["TE6"], onMrtList: true, onLrtList: false },
  { name: "Meridian", codes: ["PE2"], onMrtList: false, onLrtList: true },
  { name: "Mount Pleasant", codes: ["TE10"], onMrtList: true, onLrtList: false },
  { name: "Mountbatten", codes: ["CC7"], onMrtList: true, onLrtList: false },
  { name: "Napier", codes: ["TE12"], onMrtList: true, onLrtList: false },
  { name: "Newton", codes: ["DT11", "NS21"], onMrtList: true, onLrtList: false },
  { name: "Nibong", codes: ["PW5"], onMrtList: false, onLrtList: true },
  { name: "Nicoll Highway", codes: ["CC5"], onMrtList: true, onLrtList: false },
  { name: "Novena", codes: ["NS20"], onMrtList: true, onLrtList: false },
  { name: "Oasis", codes: ["PE6"], onMrtList: false, onLrtList: true },
  { name: "one-north", codes: ["CC23"], onMrtList: true, onLrtList: false },
  { name: "Orchard", codes: ["NS22", "TE14"], onMrtList: true, onLrtList: false },
  { name: "Orchard Boulevard", codes: ["TE13"], onMrtList: true, onLrtList: false },
  { name: "Outram Park", codes: ["EW16", "NE3", "TE17"], onMrtList: true, onLrtList: false },
  { name: "Pasir Panjang", codes: ["CC26"], onMrtList: true, onLrtList: false },
  { name: "Pasir Ris", codes: ["EW1"], onMrtList: true, onLrtList: false },
  { name: "Paya Lebar", codes: ["CC9", "EW8"], onMrtList: true, onLrtList: false },
  { name: "Pending", codes: ["BP8"], onMrtList: false, onLrtList: true },
  { name: "Petir", codes: ["BP7"], onMrtList: false, onLrtList: true },
  { name: "Phoenix", codes: ["BP5"], onMrtList: false, onLrtList: true },
  { name: "Pioneer", codes: ["EW28"], onMrtList: true, onLrtList: false },
  { name: "Potong Pasir", codes: ["NE10"], onMrtList: true, onLrtList: false },
  { name: "Promenade", codes: ["CC4", "DT15"], onMrtList: true, onLrtList: false },
  { name: "Punggol", codes: ["NE17", "PTC"], onMrtList: true, onLrtList: true },
  { name: "Punggol Coast", codes: ["NE18"], onMrtList: true, onLrtList: false },
  { name: "Punggol Point", codes: ["PW3"], onMrtList: false, onLrtList: true },
  { name: "Queenstown", codes: ["EW19"], onMrtList: true, onLrtList: false },
  { name: "Raffles Place", codes: ["EW14", "NS26"], onMrtList: true, onLrtList: false },
  { name: "Ranggung", codes: ["SE5"], onMrtList: false, onLrtList: true },
  { name: "Redhill", codes: ["EW18"], onMrtList: true, onLrtList: false },
  { name: "Renjong", codes: ["SW8"], onMrtList: false, onLrtList: true },
  { name: "Riviera", codes: ["PE4"], onMrtList: false, onLrtList: true },
  { name: "Rochor", codes: ["DT13"], onMrtList: true, onLrtList: false },
  { name: "Rumbia", codes: ["SE2"], onMrtList: false, onLrtList: true },
  { name: "Sam Kee", codes: ["PW1"], onMrtList: false, onLrtList: true },
  { name: "Samudera", codes: ["PW4"], onMrtList: false, onLrtList: true },
  { name: "Segar", codes: ["BP11"], onMrtList: false, onLrtList: true },
  { name: "Sembawang", codes: ["NS11"], onMrtList: true, onLrtList: false },
  { name: "Sengkang", codes: ["NE16", "STC"], onMrtList: true, onLrtList: true },
  { name: "Senja", codes: ["BP13"], onMrtList: false, onLrtList: true },
  { name: "Serangoon", codes: ["CC13", "NE12"], onMrtList: true, onLrtList: false },
  { name: "Shenton Way", codes: ["TE19"], onMrtList: true, onLrtList: false },
  { name: "Siglap", codes: ["TE28"], onMrtList: true, onLrtList: false },
  { name: "Simei", codes: ["EW3"], onMrtList: true, onLrtList: false },
  { name: "Sixth Avenue", codes: ["DT7"], onMrtList: true, onLrtList: false },
  { name: "Somerset", codes: ["NS23"], onMrtList: true, onLrtList: false },
  { name: "Soo Teck", codes: ["PW7"], onMrtList: false, onLrtList: true },
  { name: "South View", codes: ["BP2"], onMrtList: false, onLrtList: true },
  { name: "Springleaf", codes: ["TE4"], onMrtList: true, onLrtList: false },
  { name: "Stadium", codes: ["CC6"], onMrtList: true, onLrtList: false },
  { name: "Stevens", codes: ["DT10", "TE11"], onMrtList: true, onLrtList: false },
  { name: "Sumang", codes: ["PW6"], onMrtList: false, onLrtList: true },
  { name: "Tai Seng", codes: ["CC11"], onMrtList: true, onLrtList: false },
  { name: "Tampines", codes: ["DT32", "EW2"], onMrtList: true, onLrtList: false },
  { name: "Tampines East", codes: ["DT33"], onMrtList: true, onLrtList: false },
  { name: "Tampines West", codes: ["DT31"], onMrtList: true, onLrtList: false },
  { name: "Tan Kah Kee", codes: ["DT8"], onMrtList: true, onLrtList: false },
  { name: "Tanah Merah", codes: ["CG", "EW4"], onMrtList: true, onLrtList: false },
  { name: "Tanjong Katong", codes: ["TE25"], onMrtList: true, onLrtList: false },
  { name: "Tanjong Pagar", codes: ["EW15"], onMrtList: true, onLrtList: false },
  { name: "Tanjong Rhu", codes: ["TE23"], onMrtList: true, onLrtList: false },
  { name: "Teck Lee", codes: ["PW2"], onMrtList: false, onLrtList: true },
  { name: "Teck Whye", codes: ["BP4"], onMrtList: false, onLrtList: true },
  { name: "Telok Ayer", codes: ["DT18"], onMrtList: true, onLrtList: false },
  { name: "Telok Blangah", codes: ["CC28"], onMrtList: true, onLrtList: false },
  { name: "Thanggam", codes: ["SW4"], onMrtList: false, onLrtList: true },
  { name: "Tiong Bahru", codes: ["EW17"], onMrtList: true, onLrtList: false },
  { name: "Toa Payoh", codes: ["NS19"], onMrtList: true, onLrtList: false },
  { name: "Tongkang", codes: ["SW7"], onMrtList: false, onLrtList: true },
  { name: "Tuas Crescent", codes: ["EW31"], onMrtList: true, onLrtList: false },
  { name: "Tuas Link", codes: ["EW33"], onMrtList: true, onLrtList: false },
  { name: "Tuas West Road", codes: ["EW32"], onMrtList: true, onLrtList: false },
  { name: "Ubi", codes: ["DT27"], onMrtList: true, onLrtList: false },
  { name: "Upper Changi", codes: ["DT34"], onMrtList: true, onLrtList: false },
  { name: "Upper Thomson", codes: ["TE8"], onMrtList: true, onLrtList: false },
  { name: "Woodlands", codes: ["NS9", "TE2"], onMrtList: true, onLrtList: false },
  { name: "Woodlands North", codes: ["TE1"], onMrtList: true, onLrtList: false },
  { name: "Woodlands South", codes: ["TE3"], onMrtList: true, onLrtList: false },
  { name: "Woodleigh", codes: ["NE11"], onMrtList: true, onLrtList: false },
  { name: "Yew Tee", codes: ["NS5"], onMrtList: true, onLrtList: false },
  { name: "Yio Chu Kang", codes: ["NS15"], onMrtList: true, onLrtList: false },
  { name: "Yishun", codes: ["NS13"], onMrtList: true, onLrtList: false },
];

export const MRT_LRT_STATIONS: readonly string[] = MRT_LRT_STATION_ENTRIES.map((s) => s.name);

export const MRT_LRT_STATION_COUNT = MRT_LRT_STATIONS.length;
